//! Core data types and generator abstraction.

use indexmap::IndexMap;
use serde::Serialize;
use uuid::Uuid;

/// Represents a generated value of a supported primitive or text type.
///
/// This enum can represent any of the data types that can be generated by the library,
/// and is automatically serialized to appropriate formats when exporting to JSON, CSV, or SQL.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum Value {
    /// Null / empty value.
    None,
    /// 64-bit signed integer.
    Int(i64),
    /// 64-bit floating point number.
    Float(f64),
    /// UTF-8 text string.
    Text(String),
    /// Boolean value.
    Boolean(bool),
    /// Uuid value.
    Uuid(Uuid),
    // ColorRBG value.
    ColorRGB(u16, u16, u16),
    /// Array value containing multiple sub-values.
    Array(Vec<Value>),
    /// Object value with named fields.
    Object(IndexMap<String, Value>),
}

impl Value {
    /// Formats the value as a valid SQL literal for `INSERT INTO` queries.
    pub fn to_sql(&self) -> String {
        match self {
            Value::None => "NULL".to_string(),
            Value::Int(v) => v.to_string(),
            Value::Float(v) => v.to_string(),
            Value::Text(v) => format!("'{}'", v.replace('\'', "''")),
            Value::Boolean(v) => {
                if *v {
                    "TRUE".to_string()
                } else {
                    "FALSE".to_string()
                }
            }
            Value::Uuid(v) => format!("'{v}'"),
            Value::ColorRGB(r, g, b) => format!("RBG({r},{g},{b})"),
            Value::Array(v) => {
                let items: Vec<String> = v.iter().map(|val| val.to_sql()).collect();
                format!("ARRAY[{}]", items.join(", "))
            }
            Value::Object(map) => {
                // Serializza in formato JSON valido per colonne di tipo JSONB/JSON in SQL
                let json_str = serde_json::to_string(map).unwrap_or_else(|_| "{}".to_string());
                format!("'{}'", json_str.replace('\'', "''"))
            }
        }
    }
}

impl std::fmt::Display for Value {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Value::None => write!(f, "None"),
            Value::Int(v) => write!(f, "{v}"),
            Value::Float(v) => write!(f, "{v}"),
            Value::Text(v) => write!(f, "{v}"),
            Value::Boolean(v) => write!(f, "{v}",),
            Value::Uuid(v) => write!(f, "{v}"),
            Value::ColorRGB(r, g, b) => write!(f, "rgb({r},{g},{b})"),
            Value::Array(v) => {
                for val in v.iter() {
                    write!(f, "{val}")?;
                }
                write!(f, "")
            }
            Value::Object(map) => {
                let json = serde_json::to_string(map).unwrap_or_default();
                write!(f, "{json}")
            }
        }
    }
}

/// Trait implemented by all data generators.
///
/// This trait defines the interface for value generators. Implementations produce
/// values of type [`Value`] using a random number generator for stochastic behavior,
/// or internal state for deterministic behavior (e.g., sequential generators).
///
/// # Example
///
/// ```no_run
/// use schemagen::value::{Generator, Value};
///
/// struct MyGenerator {
///     counter: i64,
/// }
///
/// impl Generator for MyGenerator {
///     fn next_value(&mut self, _rng: &mut dyn rand::prelude::Rng) -> Value {
///         let val = self.counter;
///         self.counter += 1;
///         Value::Int(val)
///     }
/// }
/// ```
pub trait Generator {
    /// Produces the next generated [`Value`] using the provided random number generator.
    ///
    /// # Arguments
    ///
    /// * `rng` - A random number generator. For deterministic generators (like [`Sequential`](crate::generators::sequential::Sequential)),
    ///   this parameter may be ignored.
    ///
    /// # Returns
    ///
    /// The next [`Value`] in the generation sequence.
    fn next_value(&mut self, rng: &mut dyn rand::Rng) -> Value;
}
